# Generated by Django 3.2.13 on 2022-08-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageloggerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image_loagger',
            new_name='image_logger',
        ),
    ]
