# Generated by Django 3.2.13 on 2022-09-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageloggerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image_logger',
            new_name='ImageInfoModel',
        ),
    ]
